# Generated by Django 3.1.2 on 2020-10-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MisAlarmCommand',
            fields=[
                ('id', models.IntegerField(auto_created=True, db_column='id', primary_key=True, serialize=False)),
                ('command', models.CharField(db_column='command', max_length=2000)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mis_alarm_commands',
            },
        ),
    ]
