# Generated by Django 3.1.2 on 2020-10-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misalarm', '0002_auto_20201012_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.CharField(db_column='ip_addr', max_length=16)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'new_business_ip',
            },
        ),
    ]
