version: "3"
services:
  web:
    build: web-cmd-detections-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    # image: "mariadb:10.5.6-focal"
    build: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "wodemima"
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin:5"
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: "db"
      MYSQL_ROOT_PASSWORD: "wodemima"
      PMA_ARBITRARY: 1
    depends_on:
      - db
