version: "3"
services:
  web:
    build: web
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - cmd-detect-backend
  db:
    # image: "mariadb:10.5.6-focal"
    build: mysql
    restart: always
    privileged: true
    volumes:
      - ./mysql/data/:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "wodemima"
    networks:
      - cmd-detect-backend
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin:5"
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: "db"
      MYSQL_ROOT_PASSWORD: "wodemima"
      PMA_ARBITRARY: 1
    depends_on:
      - db
    networks:
      - cmd-detect-backend

networks:
  cmd-detect-backend:
    driver: bridge
